# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build k8s-example-project`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t k8s-example-project`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system k8s-example-project && \
          adduser --system -G k8s-example-project k8s-example-project

COPY dist/k8s-example-project k8s-example-project/
RUN chown -R k8s-example-project:k8s-example-project .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix k8s-example-project --omit=dev -f install

CMD [ "node", "k8s-example-project" ]
