apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  ports:
  - port: 27017
    targetPort: 27017


apiVersion: v1
kind: Endpoints
metadata:
  name: mongo-service
subsets:
  - addresses:
      - ip: 55.2.33.111
    ports:
      - port: 27017