apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: client-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: client-api
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

---

apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: client-api-vpa
  namespace: default
spec:
  scaleTargetRef:
    kind: Deployment
    name: client-api
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: "100m"
          memory: "128Mi"
        maxAllowed:
          cpu: "500m"
          memory: "512Mi"



  maxReplicas: 10