apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: client-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: client-api
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80